---
- name: Install repos
  package:
    name: epel-release
    state: present

- name: Install Gluster repository
  package:
    name: centos-release-gluster
    state: present

- name: Install Infiniband packages
  package:
    name:
      - '@InfiniBand Support'
      - perftest
      - infiniband-diags
      - glusterfs-rdma
    state: present
  when: gluster_cluster_transport_mode == "rdma"

- name: Install Gluster client packages
  package:
    name:
      - glusterfs-client
      - glusterfs-fuse
    state: present

- name: Start and enable RDMA service (loads required kernel modules)
  service:
    name: rdma
    enabled: yes
    state: started
  when: gluster_cluster_transport_mode == "rdma"

- name: Check if mount directory exists
  file:
    path: "{{ gluster_cluster_client_mntpoint }}"
    state: directory

- name: Mount the filesystem
  mount:
    path: "{{ gluster_cluster_client_mntpoint }}"
    src: "{{ gluster_cluster_hosts }}:{{ gluster_cluster_volume_name }}"
    fstype: glusterfs
    state: mounted
