---
- name: If gluster-servers is present
  include: servers.yml
  when: gluster_enable.servers | bool

- name: If gluster-clients is present
  include: clients.yml
  when: gluster_enable.clients | bool
