---

- name: Install EPEL release
  package:
    name: epel-release
    state: present

- name: Install Gluster repository
  package:
    name: centos-release-gluster
    state: latest

- name: Populate service facts
  service_facts:

- name: Stop glusterd
  service:
    name: glusterd
    state: stopped
  when: "'glusterd.service' in ansible_facts.services"

- name: Format bricks
  filesystem:
    fstype: xfs
    opts: -f -i size=512 -n size=8192 -d su=128k,sw=10
    dev: "/dev/{{ item }}"
  with_items: "{{ gluster_cluster_block_devices }}"

- name: Update fstab and mount bricks
  mount:
    src: "/dev/{{ item }}"
    path: "{{ gluster_cluster_volume_base_path }}/{{ gluster_cluster_volume_name }}/{{ item }}"
    fstype: xfs
    state: mounted
    opts: rw,inode64,noatime,nouuid
  with_items: "{{ gluster_cluster_block_devices }}"

- name: Install Infiniband packages
  package:
    name:
      - '@InfiniBand Support'
      - perftest
      - infiniband-diags
      - glusterfs-rdma
    state: latest
  when: gluster_cluster_transport_mode == "rdma"

- name: Install Gluster server package
  package:
    name: glusterfs-server
    state: latest

- name: Start and enable RDMA service (loads required kernel modules)
  service:
    name: rdma
    enabled: yes
    state: started
  when: gluster_cluster_transport_mode == "rdma"

- name: Start and enable glusterd
  service:
    name: glusterd
    enabled: yes
    state: started

- name: Create a trusted storage pool
  gluster_peer:
    nodes: "{{ gluster_cluster_hosts }}"
    state: present
  run_once: true

- name: Create Gluster volume
  gluster_volume:
    name: "{{ gluster_cluster_volume_name }}"
    state: present
    bricks: >-
      {%- for item in gluster_cluster_block_devices -%}
      {{ gluster_cluster_volume_base_path }}/{{ gluster_cluster_volume_name }}/{{ item }}/brick{%- if not loop.last -%},{%- endif -%}
      {%- endfor -%}
    force: true
    cluster: "{{ gluster_cluster_hosts }}"
    transport: "{{ gluster_cluster_transport_mode }}"
    disperses: "{{ gluster_cluster_disperses | default(0) }}"
    stripes: "{{ gluster_cluster_stripes | default(0) }}"
    replicas: "{{ gluster_cluster_replicas | default(0) }}"
    redundancies: "{{ gluster_cluster_redundancies | default(0) }}"
    options: "{{ gluster_cluster_volume_options | default(omit) }}"
  run_once: true

- name: Ensure Gluster volume is started
  gluster_volume:
    name: "{{ gluster_cluster_volume_name }}"
    state: started
  run_once: true
